import { Property } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getPlaceholder = (id: string) => {
  return PlaceHolderImages.find(img => img.id === id)?.imageUrl || `https://picsum.photos/seed/${id}/1200/800`;
};

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Luxury Modern American Villa',
    type: 'Buy',
    category: 'Modern Villa',
    location: 'Beverly Hills, CA',
    price: '$4,500,000',
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6500,
    description: 'A stunning architectural masterpiece offering panoramic views and state-of-the-art smart home features. Located in the heart of Beverly Hills, this villa features an open-concept design, floor-to-ceiling windows, and a chef\'s kitchen with top-of-the-line appliances.',
    amenities: ['Swimming Pool', 'Smart Home System', 'Wine Cellar', 'Home Theater', 'Gated Security'],
    imageUrl: getPlaceholder('luxury-villa'),
    featured: true,
  },
  {
    id: '2',
    title: 'Suburban Family Haven',
    type: 'Buy',
    category: 'Suburban House',
    location: 'Plano, TX',
    price: '$750,000',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    description: 'Spacious backyard and modern kitchen, perfect for a growing family in a safe neighborhood. This home is situated in a highly-rated school district and features a recently renovated master suite and a large patio for entertaining.',
    amenities: ['Large Backyard', 'Modern Kitchen', 'Double Garage', 'Quiet Street', 'Solar Panels'],
    imageUrl: getPlaceholder('suburban-home'),
    featured: true,
  },
  {
    id: '3',
    title: 'Downtown Skyline Penthouse',
    type: 'Rent',
    category: 'Downtown Apartment',
    location: 'Chicago, IL',
    price: '$4,200/mo',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    description: 'High-rise living with floor-to-ceiling windows and premium building amenities. Enjoy breathtaking views of the Chicago skyline from your private balcony. The building offers 24/7 concierge service and a state-of-the-art fitness center.',
    amenities: ['24/7 Concierge', 'Fitness Center', 'Rooftop Lounge', 'Parking', 'Storage Unit'],
    imageUrl: getPlaceholder('downtown-apartment'),
    featured: true,
  },
  {
    id: '4',
    title: 'Coastal Waterfront Estate',
    type: 'Buy',
    category: 'Waterfront Property',
    location: 'Miami, FL',
    price: '$2,800,000',
    bedrooms: 4,
    bathrooms: 4,
    sqft: 4200,
    description: 'Direct ocean access with private dock and expansive outdoor entertaining spaces. This estate is perfect for boat lovers and features a luxury infinity pool overlooking the bay.',
    amenities: ['Private Dock', 'Ocean View', 'Outdoor Kitchen', 'Guest House', 'Infinity Pool'],
    imageUrl: getPlaceholder('waterfront-property'),
  },
  {
    id: '5',
    title: 'Luxury Condo on Fifth Ave',
    type: 'Rent',
    category: 'Luxury Condo',
    location: 'Manhattan, NY',
    price: '$6,500/mo',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 900,
    description: 'Exquisite city views and top-of-the-line finishes in the heart of Manhattan. This condo features white oak flooring, marble countertops, and custom cabinetry throughout.',
    amenities: ['Prime Location', 'Washer/Dryer', 'Hardwood Floors', 'Gym', 'Valet Parking'],
    imageUrl: getPlaceholder('luxury-condo'),
  },
  {
    id: '6',
    title: 'Modern Studio in Tech Hub',
    type: 'Rent',
    category: 'Studio Flat',
    location: 'Seattle, WA',
    price: '$2,100/mo',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 550,
    description: 'Minimalist studio perfect for young professionals, close to major tech campuses. Includes built-in storage solutions and high-speed fiber optic internet capability.',
    amenities: ['Walking Distance to Work', 'High-Speed Internet', 'Modern Appliances', 'Bike Storage'],
    imageUrl: getPlaceholder('studio-flat'),
  },
  {
    id: '7',
    title: 'Smart Tech Suburban Home',
    type: 'Buy',
    category: 'Suburban House',
    location: 'San Jose, CA',
    price: '$1,850,000',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    description: 'A newly built smart home featuring integrated voice control for lighting, climate, and security. Energy-efficient design with EV charging station included.',
    amenities: ['Smart Lighting', 'EV Charging', 'Home Office', 'Gourmet Kitchen'],
    imageUrl: getPlaceholder('smart-home'),
  },
  {
    id: '8',
    title: 'Family Retreat Rental',
    type: 'Rent',
    category: 'Family Rental Home',
    location: 'Orlando, FL',
    price: '$3,100/mo',
    bedrooms: 4,
    bathrooms: 2,
    sqft: 2400,
    description: 'Comfortable family home located in a gated community. Features a screened-in porch and easy access to local parks and theme parks.',
    amenities: ['Gated Community', 'Screened Porch', 'Central Air', 'Playground Access'],
    imageUrl: getPlaceholder('family-rental'),
  },
];
